services:
  php:
    build: ./app
    container_name: php-container
    volumes:
      - ./app:/var/www/html
    ports:
      - 8081:80
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123.
      - POSTGRES_DB=agencia_viajes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=a22julioaa@iessanclemente.net
      - PGADMIN_DEFAULT_PASSWORD=abc123.
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  postgres_data:
